name: CI Plan

on:
  push:
    branches:
      - main
      - 'feature/**'
      - '*'
  pull_request:
    branches:
      - main

jobs:
  terragrunt:
    name: "Terraform with Terragrunt"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/irfan-ssh/terragrunt-docker-image:latest # Replace with your actual image

    env:
      TERRAGRUNT_TFPATH: /usr/local/bin/terraform
      tf_working_dir: './terragrunt-code'

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Verify Terraform and Terragrunt Installation
        run: |
          ls -ashl
          tfenv install 1.8.5
          tgenv install 0.60.0
          tfenv use 1.8.5
          tgenv use 0.60.0
          terraform --version
          terragrunt --version
        working-directory: ${{ env.tf_working_dir }}

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run HCL Format
        working-directory: ${{ env.tf_working_dir }}
        run: terragrunt hclfmt

      - name: Init Terragrunt
        working-directory: ${{ env.tf_working_dir }}
        run: terragrunt run-all init --terragrunt-non-interactive

      - name: Plan Terragrunt
        working-directory: ${{ env.tf_working_dir }}
        run: |
          terragrunt run-all plan --terragrunt-non-interactive
          # Optional: Save plan output
          # terragrunt run-all plan --out=terraform.tfplan